; 変更する場合は値の先頭のセミコロンを消してください
[Setting]
; 受信したコメントのログファイルへの記録モードを指定
; # 0 = 一切記録しない (デフォルト)
; # 1 = 録画中だけ記録する
; # 2 = すべて記録する
;logfileMode=0

; サーバ(.nicovideo.jp)に渡すクッキーを出力するコマンドを指定
; # 詳しくは説明ファイルを参照してください (デフォルトは未指定)
; # サーバとの通信はすべてセキュアプロトコル(TLS)で行われます
; # jkcnslにログイン処理をまかせる場合は設定不要です
; # 後述のrefugeUriが指定されていてrefugeMixing=0のとき、コマンドは実行されません
; # POSIXのpopen関数を popen("env --default-signal timeout 10s {execGetCookie}", "r") の形で呼び出すので、複数コマンドになるときは sh -c "..." などシェルを噛ませてください
; # 出力は key=value<改行>key=value<改行>... となるようにしてください
; # 終了ステータスが0でないなど不正なときは未指定と同じ扱いになります
;execGetCookie=

; NX-Jikkyo・避難所のWebSocketのアドレス(wss://～)を指定 (デフォルトは未指定)
; # クッキーは送信しません
; # アドレス中の{jkID}は実況の番号(jk?)、{chatStreamID}はチャットのID(ch???やlv???など)に置換されます
; # NX-Jikkyoの指定例
;refugeUri=wss://nx-jikkyo.tsukumijima.net/api/v1/channels/{jkID}/ws/watch

; NX-Jikkyo・避難所から受信したコメントのうち、ニコニコ実況から転送されたものを除去するかどうか (デフォルトは 0 = しない)
;dropForwardedComment=1

; NX-Jikkyo・避難所とニコニコ実況の両方に接続するかどうか
; # 0 = refugeUriが指定されていればNX-Jikkyo・避難所のみ、指定されていなければニコニコ実況のみに接続する (デフォルト)
; # 1 = refugeUriが指定されていれば両方に接続する
;refugeMixing=1

; 匿名(184)でコメント投稿するか (デフォルトは 1 = する)
;anonymity=1

[Channels]
; デジタル放送のサービスIDと、実況の番号(jk?)
; # キーの下4桁の16進数にはサービスIDを、上1桁にはネットワークID（ただし地上波は15=0xFとする）を指定してください
; # あらかじめjkch.sh.txtにあるリストで対応付けているので、大体の地域で基本的に設定不要（のはず）です
; # 例:テレビ東京(0x0430)をjk7と対応づけたいとき
;0xF0430=7
; # 例:NHK BS(0x0065)とデフォルト(jk101)との対応付けを解除したいとき
;0x40065=-1

[ChatStreams]
; 実況の番号(jk?)と、チャットのID(ch???やlv???など)
; # あらかじめ2024年時点のニコニコ実況(jk.nicovideo.jpの公式チャンネルのみ)で対応付けています
; # jk7の対応づけを変更したいとき
;7=ch???

; # 対応付けを解除したいときは空文字列にしてください
; # jk7はどこにも接続したくないとき
;7=

; # ニコニコ実況とNX-Jikkyo・避難所について個別に対応づけたいときはカンマで区切ってください
; # カンマの右側がNX-Jikkyo・避難所です
; # jk7はニコニコ実況だけにしたいとき
;7=ch2646441,
; # jk7はNX-Jikkyo・避難所だけにしたいとき("NX"の部分は任意の英数字)
;7=,NX

; # 下記は2025/02/06現在存在しているNX-Jikkyoのチャンネルを記載しています
; # 10=テレ玉 11=tvk 12=チバテレ 13=サンテレビ 14=KBS京都 103=NHK BSプレミアム 141=BS日テレ 151=BS朝日 161=BS-TBS 171=BSテレ東
; # 181=BSフジ 191=WOWOW PRIME 192=WOWOW LIVE 193=WOWOW CINEMA 200=BS10 201=BS10スターチャンネル 222=BS12 236=BSアニマックス
; # 252=WOWOW PLUS 260=BS松竹東急 265=BSよしもと 333=AT-X
10=,NX
11=,NX
12=,NX
13=,NX
14=,NX
103=,NX
141=,NX
151=,NX
161=,NX
171=,NX
181=,NX
191=,NX
192=,NX
193=,NX
200=,NX
201=,NX
222=,NX
236=,NX
252=,NX
260=,NX
265=,NX
333=,NX
